version: 2
jobs:
  python3:
    working_directory: ~/sllurp
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-py3-dependencies-{{ checksum "setup.py" }}
            - v1-py3-dependencies-
      - run:
          name: install python3 dependencies
          command: |
            python3 -m venv .venv3
            . .venv3/bin/activate
            pip3 install -e .[test]
      - save_cache:
          paths:
            - ".venv3"
          key: v1-py3-dependencies-{{ checksum "setup.py" }}
      - run:
          name: run python3 tests
          command: |
            . .venv3/bin/activate
            python3 setup.py test
workflows:
  version: 2
  py3:
    jobs:
      - python3
